apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    deployment: msa-linuxme
    {{- include "msa.labels" . | nindent 4 }}
  name: msa-linuxme
spec:
  replicas: {{ .Values.msa_linuxme.replicas }}
  selector:
    matchLabels:
      deployment: msa-linuxme
      {{- include "msa.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        deployment: msa-linuxme
        {{- include "msa.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: msa-linuxme
          image:  "{{ .Values.msa_linuxme.image }}"
          securityContext:
            privileged: true
          ports:
            - containerPort: 22
          volumeMounts:
            - name: dev-mem
              mountPath: /dev/mem
      volumes:
        - name: dev-mem
          hostPath:
            path: /dev/mem
      restartPolicy: Always

