apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    deployment: msa-monitoring
    {{- include "msa.labels" . | nindent 4 }}
  name: msa-monitoring
spec:
  replicas: {{ .Values.msa_monitoring.replicas }}
  selector:
    matchLabels:
      deployment: msa-monitoring
      {{- include "msa.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        deployment: msa-monitoring
        {{- include "msa.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - env:
            - name: ES_CREDENTIALS
              value: c3VwZXJ1c2VyOnheWnl1R002fnU9K2ZZMkc=
          image: "{{ .Values.msa_monitoring.image }}"
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - /etc/init.d/ubi-poll status | grep -q 'service seems UP' || exit 1
          name: msa-monitoring
          resources:
            requests:
              memory: "100Mi"
              cpu: "100m"
          volumeMounts:
            - mountPath: /opt/devops/
              name: msa-dev
            - mountPath: /opt/fmc_entities
              name: msa-entities
            - mountPath: /opt/fmc_repository
              name: msa-repository
            - mountPath: /opt/rrd
              name: rrd-repository
            - mountPath: /opt/sms/spool/parser
              name: msa-monitbulkfiles
      volumes:
        - name: msa-dev
          persistentVolumeClaim:
            claimName: msa-dev
        - name: msa-entities
          persistentVolumeClaim:
            claimName: msa-entities
        - name: msa-repository
          persistentVolumeClaim:
            claimName: msa-repository
        - name: rrd-repository
          persistentVolumeClaim:
            claimName: rrd-repository
        - name: msa-monitbulkfiles
          persistentVolumeClaim:
            claimName: msa-monitbulkfiles
