apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    deployment: msa-front
    {{- include "msa.labels" . | nindent 4 }}
  name: msa-front
spec:
  replicas: {{ .Values.msa_front.replicas }}
  selector:
    matchLabels:
      deployment: msa-front
      {{- include "msa.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        deployment: msa-front
        {{- include "msa.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - image: "{{ .Values.msa_front.image }}"
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - curl -k --fail https://localhost
          name: msa-front
          resources:
            requests:
              memory: "100Mi"
              cpu: "100m"
          ports:
            - containerPort: 80
            - containerPort: 443
            - containerPort: 162
              protocol: UDP
            - containerPort: 69
              protocol: UDP
            - containerPort: 5200
              protocol: UDP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: msa-front
    {{- include "msa.labels" . | nindent 4 }}
  name: msa-front
spec:
  ports:
    - name: "80"
      port: 80
      targetPort: 80
    - name: "443"
      port: 443
      targetPort: 443
    - name: "162"
      port: 162
      protocol: UDP
      targetPort: 162
    - name: "69"
      port: 69
      protocol: UDP
      targetPort: 69
    - name: "5200"
      port: 5200
      protocol: UDP
      targetPort: 5200
  selector:
    deployment: msa-front
    {{- include "msa.selectorLabels" . | nindent 4 }}


---
{{- if .Values.msa_front.loadbalancer -}}

apiVersion: v1
kind: Service
metadata:
  labels:
    service: msa-front-lb
    {{- include "msa.labels" . | nindent 4 }}
  name: msa-front-lb
spec:
  type: LoadBalancer
  ports:
    - name: "443"
      port: 443
      targetPort: 443
  selector:
    deployment: msa-front
    {{- include "msa.selectorLabels" . | nindent 4 }}

{{- end -}}