apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    deployment: msa-rsyslog
    {{- include "msa.labels" . | nindent 4 }}
  name: msa-rsyslog
spec:
  replicas: {{ .Values.msa_rsyslog.replicas }}
  selector:
    matchLabels:
      deployment: msa-rsyslog
      {{- include "msa.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        deployment: msa-rsyslog
        {{- include "msa.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - image: "{{ .Values.msa_rsyslog.image }}"
          name: msa-rsyslog
          resources:
            requests:
              memory: "500Mi"
              cpu: "300m"
          ports:
            - containerPort: 514
              protocol: UDP
            - containerPort: 514
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: msa-rsyslog
    {{- include "msa.labels" . | nindent 4 }}
  name: msa-rsyslog
spec:
  ports:
    - name: "514"
      port: 514
      protocol: UDP
      targetPort: 514
    - name: 514-tcp
      port: 514
      targetPort: 514
  selector:
    deployment: msa-rsyslog
    {{- include "msa.selectorLabels" . | nindent 4 }}

