apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    deployment: msa-alarm
    {{- include "msa.labels" . | nindent 4 }}
  name: msa-alarm
spec:
  replicas: {{ .Values.msa_alarm.replicas }}
  selector:
    matchLabels:
      deployment: msa-alarm
      {{- include "msa.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        deployment: msa-alarm
        {{- include "msa.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - env:
            - name: ES_CREDENTIALS
              value: c3VwZXJ1c2VyOnheWnl1R002fnU9K2ZZMkc=
          image: "{{ .Values.msa_alarm.image }}"
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - /etc/init.d/ubi-alarm status | grep -q 'service seems UP' || exit 1
          name: msa-alarm
          resources:
            requests:
              memory: "100Mi"
              cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: msa-alarm
    {{- include "msa.labels" . | nindent 4 }}
  name: msa-alarm
spec:
  ports:
    - name: "28164"
      port: 28164
      targetPort: 28164
  selector:
    deployment: msa-alarm
    {{- include "msa.selectorLabels" . | nindent 4 }}
