apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    deployment: msa-bud
    {{- include "msa.labels" . | nindent 4 }}
  name: msa-bud
spec:
  replicas: {{ .Values.msa_bud.replicas }}
  selector:
    matchLabels:
      deployment: msa-bud
      {{- include "msa.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        deployment: msa-bud
        {{- include "msa.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - image: "{{ .Values.msa_bud.image }}"
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - /etc/init.d/ubi-bud status | grep -q 'service seems UP' || exit 1
          name: msa-bud
          resources:
            requests:
              memory: "100Mi"
              cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: msa-bud
    {{- include "msa.labels" . | nindent 4 }}
  name: msa-bud
spec:
  ports:
    - name: "28170"
      port: 28170
      targetPort: 28170
  selector:
    deployment: msa-bud
    {{- include "msa.selectorLabels" . | nindent 4 }}
