apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    deployment: msa-sms
    {{- include "msa.labels" . | nindent 4 }}
  name: msa-sms
spec:
  replicas: {{ .Values.msa_sms.replicas }}
  selector:
    matchLabels:
      deployment: msa-sms
      {{- include "msa.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        deployment: msa-sms
        {{- include "msa.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - env:
            - name: ES_CREDENTIALS
              value: c3VwZXJ1c2VyOnheWnl1R002fnU9K2ZZMkc=
          image: "{{ .Values.msa_sms.image }}"
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - /etc/init.d/ubi-sms status | grep -q 'service seems UP' || exit 1
          name: msa-sms
          resources:
            requests:
              memory: "500Mi"
              cpu: "300m"
          volumeMounts:
            - mountPath: /opt/devops/
              name: msa-dev
            - mountPath: /opt/fmc_entities
              name: msa-entities
            - mountPath: /opt/fmc_repository
              name: msa-repository
            - mountPath: /opt/svnroot
              name: msa-svn
            - mountPath: /opt/sms/spool/routerconfigs
              name: msa-svn-ws
            - mountPath: /opt/sms/spool/parser
              name: msa-bulkfiles
      volumes:
        - name: msa-dev
          persistentVolumeClaim:
            claimName: msa-dev
        - name: msa-entities
          persistentVolumeClaim:
            claimName: msa-entities
        - name: msa-repository
          persistentVolumeClaim:
            claimName: msa-repository
        - name: msa-svn
          persistentVolumeClaim:
            claimName: msa-svn
        - name: msa-svn-ws
          persistentVolumeClaim:
            claimName: msa-svn-ws
        - name: msa-bulkfiles
          persistentVolumeClaim:
            claimName: msa-bulkfiles
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: msa-sms
    {{- include "msa.labels" . | nindent 4 }}
  name: msa-sms
spec:
  ports:
    - name: "28165"
      port: 28165
      targetPort: 28165
    - name: "28169"
      port: 28169
      targetPort: 28169
    - name: "3690"
      port: 3690
      targetPort: 3690
    - name: "28172"
      port: 28172
      targetPort: 28172
  selector:
    deployment: msa-sms
    {{- include "msa.selectorLabels" . | nindent 4 }}