apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    {{- include "msa.labels" . | nindent 4 }}
  name: msa-api-keystore
spec:
  accessModes:
    - ReadWriteOnce
  {{ if .Values.defaultStorageClass }}storageClassName:  "{{ .Values.defaultStorageClass }}"  {{ end }}
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    {{- include "msa.labels" . | nindent 4 }}
  name: msa-api-logs
spec:
  accessModes:
    - ReadWriteOnce
  {{ if .Values.defaultStorageClass }}storageClassName:  "{{ .Values.defaultStorageClass }}"  {{ end }}

  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    {{- include "msa.labels" . | nindent 4 }}
  name: msa-api
spec:
  accessModes:
    - ReadWriteOnce
  {{ if .Values.defaultStorageClass }}storageClassName:  "{{ .Values.defaultStorageClass }}"  {{ end }}

  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    {{- include "msa.labels" . | nindent 4 }}
  name: msa-bulkfiles
spec:
  accessModes:
    - ReadWriteOnce
  {{ if .Values.defaultStorageClass }}storageClassName:  "{{ .Values.defaultStorageClass }}"  {{ end }}

  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    {{- include "msa.labels" . | nindent 4 }}
  name: msa-dev
spec:
  accessModes:
    - ReadWriteOnce
  {{ if .Values.defaultStorageClass }}storageClassName:  "{{ .Values.defaultStorageClass }}"  {{ end }}

  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    {{- include "msa.labels" . | nindent 4 }}
  name: msa-entities
spec:
  accessModes:
    - ReadWriteOnce
  {{ if .Values.defaultStorageClass }}storageClassName:  "{{ .Values.defaultStorageClass }}"  {{ end }}

  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    {{- include "msa.labels" . | nindent 4 }}
  name: msa-es
spec:
  accessModes:
    - ReadWriteOnce
  {{ if .Values.defaultStorageClass }}storageClassName:  "{{ .Values.defaultStorageClass }}"  {{ end }}

  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    {{- include "msa.labels" . | nindent 4 }}
  name: msa-monitbulkfiles
spec:
  accessModes:
    - ReadWriteOnce
  {{ if .Values.defaultStorageClass }}storageClassName:  "{{ .Values.defaultStorageClass }}"  {{ end }}

  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    {{- include "msa.labels" . | nindent 4 }}
  name: msa-repository
spec:
  accessModes:
    - ReadWriteOnce
  {{ if .Values.defaultStorageClass }}storageClassName:  "{{ .Values.defaultStorageClass }}"  {{ end }}
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    {{- include "msa.labels" . | nindent 4 }}
  name: msa-svn
spec:
  accessModes:
    - ReadWriteOnce
  {{ if .Values.defaultStorageClass }}storageClassName:  "{{ .Values.defaultStorageClass }}"  {{ end }}
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    {{- include "msa.labels" . | nindent 4 }}
  name: msa-db
spec:
  accessModes:
    - ReadWriteOnce
  {{ if .Values.defaultStorageClass }}storageClassName:  "{{ .Values.defaultStorageClass }}"  {{ end }}
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    {{- include "msa.labels" . | nindent 4 }}
  name: msa-svn-ws
spec:
  accessModes:
    - ReadWriteOnce
  {{ if .Values.defaultStorageClass }}storageClassName:  "{{ .Values.defaultStorageClass }}"  {{ end }}
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rrd-repository
spec:
  accessModes:
    - ReadWriteOnce
  {{ if .Values.defaultStorageClass }}storageClassName:  "{{ .Values.defaultStorageClass }}"  {{ end }}
  resources:
    requests:
      storage: 100Mi