apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.24.0 (4a2a0458)
  creationTimestamp: null
  labels:
    io.kompose.service: db
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: db
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.24.0 (4a2a0458)
      creationTimestamp: null
      labels:
        io.kompose.network/quickstart-default: "true"
        io.kompose.service: db
    spec:
      containers:
        - args:
            - postgres
            - -c
            - max_connections=800
            - -c
            - max_prepared_transactions=100
          env:
            - name: CAMUNDA_DB
              value: process-engine
            - name: CAMUNDA_PASSWORD
              value: camunda
            - name: CAMUNDA_USER
              value: camunda
            - name: POSTGRES_DB
              value: POSTGRESQL
            - name: POSTGRES_PASSWORD
              value: my_db_password
            - name: PGDATA
              value: /var/lib/postgresql/data
          image: openmsa/openmsa:msa2-db-2.6.0GA-c00fdfaa09c44105f71a0e2d21467a9458f63921
          livenessProbe:
            exec:
              command:
                - pg_isready -U postgres
            failureThreshold: 5
            periodSeconds: 30
            timeoutSeconds: 60
          name: msa-db
          ports:
            - containerPort: 5432
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/postgresql
              name: msa-db
      restartPolicy: Always
      volumes:
        - name: msa-db
          persistentVolumeClaim:
            claimName: msa-db
status: {}
