apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.24.0 (4a2a0458)
  creationTimestamp: null
  labels:
    io.kompose.service: msa-alarm
  name: msa-alarm
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: msa-alarm
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.24.0 (4a2a0458)
      creationTimestamp: null
      labels:
        io.kompose.network/quickstart-default: "true"
        io.kompose.service: msa-alarm
    spec:
      containers:
        - env:
            - name: ES_CREDENTIALS
              value: c3VwZXJ1c2VyOnheWnl1R002fnU9K2ZZMkc=
          image: openmsa/openmsa:msa2-alarm-2.6.0GA-d4255679b87051afc998cf791139b19b77b4f124
          livenessProbe:
            exec:
              command:
                - /etc/init.d/ubi-alarm status | grep -q 'service seems UP' || exit 1
          name: msa-alarm
          ports:
            - containerPort: 28164
          resources: {}
          volumeMounts:
            - mountPath: /opt/sms/logs
              name: msa-sms-logs
      restartPolicy: Always
      volumes:
        - name: msa-sms-logs
          persistentVolumeClaim:
            claimName: msa-sms-logs
status: {}
