apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.24.0 (4a2a0458)
  creationTimestamp: null
  labels:
    io.kompose.service: msa-alarm
  name: msa-alarm
spec:
  ports:
    - name: "28164"
      port: 28164
      targetPort: 28164
  selector:
    io.kompose.service: msa-alarm
status:
  loadBalancer: {}
