apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.24.0 (4a2a0458)
  creationTimestamp: null
  labels:
    io.kompose.service: msa-es
  name: msa-es
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: msa-es
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.24.0 (4a2a0458)
      creationTimestamp: null
      labels:
        io.kompose.network/quickstart-default: "true"
        io.kompose.service: msa-es
    spec:
      containers:
        - env:
            - name: ES_CREDENTIALS
              value: c3VwZXJ1c2VyOnheWnl1R002fnU9K2ZZMkc=
            - name: ES_JAVA_OPTS
              value: -Xms512m -Xmx1024m
            - name: bootstrap.memory_lock
              value: "true"
            - name: discovery.type
              value: single-node
            - name: script.painless.regex.enabled
              value: "true"
            - name: xpack.security.enabled
              value: "true"
          image: openmsa/openmsa:msa2-es-2.6.0GA-fe57dfc7ecc70dff2feac67fc3b343bc5fbdba11
          livenessProbe:
            exec:
              command:
                - 'test -f /home/install/init-done && curl -s -XGET -H ''Authorization: Basic c3VwZXJ1c2VyOnheWnl1R002fnU9K2ZZMkc=''  ''http://localhost:9200/_cluster/health?pretty'' | grep -q ''status.*green'' || exit 1'
            failureThreshold: 10
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 2
          name: msa-es
          ports:
            - containerPort: 9200
          resources: {}
          volumeMounts:
            - mountPath: /usr/share/elasticsearch/data
              name: msa-es
      restartPolicy: Always
      volumes:
        - name: msa-es
          persistentVolumeClaim:
            claimName: msa-es
status: {}
