apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-app
spec:
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: myapp
        image: wordpress:latest
        envFrom:
        - configMapRef:
            name: wp-config
        ports:
        - containerPort: 80
